name = "SFGToolsScripts"
uuid = "7bddf194-b1ca-11e8-3e63-93a44d46942c"
authors = ["MLackner <lacknersmichael@gmail.com>"]
version = "0.1.0"

[deps]
AndorSIF = "d04cd5f8-5917-4006-ac6f-d139328806a7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SFGTools = "27cad0a0-9c7d-4dc4-9a71-c2cc5f520b28"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TerminalMenus = "dc548174-15c3-5faf-af27-7997cfbde655"
